# Permissions necessary to use the Azure/login action.
# Even if you grant read/write at the repo level, you still need id-token.
permissions:
  contents: read
  pages: write
  id-token: write

name: DEV - Train Model

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [dev]
    paths:
      - Pipeline/config/**
      - Pipeline/scripts/**
      - Pipeline/deploy-train.py
      - Pipeline/requirements.txt
      - .github/workflows/train_model.yml

jobs:
  deploy_ml_training_pipeline:
    name: DEV - Deploy the Training pipeline to Azure ML
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - name: Repo checkout
      uses: actions/checkout@v3
    - name: Install az CLI
      run: |
        # Install the az CLI and ML extension
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az extension add -n ml -y
        echo "Installed Azure CLI and ML extension"
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    - name: Install and prepare Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Run AML pipeline
      run: |
        echo "Installing dependencies"
        cd Pipeline/
        python -m pip install -r requirements.txt
        echo "Run training pipeline"
        # Run training pipeline
        python deploy-train.py